### ISSUE TITLE
Consistency of argument names in get_ausplots with their output tables

### ISSUE THREAD

**Issue by GregGuerin** [ternaustralia/ausplotsR#11]
At present, the formatting of names for different Ausplots modules can be confusing because it differs between the argument in the get_ausplots function and the name of the tables in the outputs. This was done deliberately to separate input from output in preparing the code but could be frustrating to users.

e.g.
veg.vouchers | veg.vouch
site_info | site.info
soil_character |  soil.char

Perhaps the formatting change from input to output should at least be consistent.

**This change may break existing code using the package**

Do we tidy this up or live with it to avoid breaking code?

**Comment by tomsaleeba** [comment]
Are there real users having troubles with this or are we just guessing it's annoying them? It's just that breaking changes may end up causing more problems for our user community if user who weren't that annoyed by the naming thing suddenly have their code break.

**Comment by GregGuerin** [comment]
It was pointed out internally as a little confusing, that is all. In practice, you can see the names of all the tables returned by get_auplots by running e.g. names(my.ausplots.extract).

I agree we should leave it now as changing the function arguments or the names of the corresponding data tables will break code.
