### ISSUE TITLE
Handle incorrect SiteName in Query more gracefully

### ISSUE THREAD

**Issue by tokmakoff** [ternaustralia/ausplotsR#13]
When a user queries for a site and supplies an incorrect (or bogus) SiteName, an error is returned which is a bit cryptic.

We should trap the fact that no sites are returned and handle that gracefully.

```
get_ausplots(my.Plot_IDs="ILIKECOKE", site_info=TRUE, structural_summaries=FALSE,
             veg.vouchers=FALSE, veg.PI=FALSE, basal.wedge=FALSE, soil_subsites=FALSE,
             soil_bulk_density=FALSE, soil_character=FALSE, bounding_box="none",
             species_name_search=NULL)
Error in get_ausplots(my.Plot_IDs = "ILIKECOKE", site_info = TRUE, structural_summaries = FALSE,  : 
  Plot_IDs must be provided as a character vector.
```

**Comment by GregGuerin** [comment]
Thanks for picking this up - I think it is corrected now. It had been checking that the input was in the correct format but checking that on the internally returned list of plots that matched, which was empty if there were no matches. I updated to check the original user input, so it should now return an error that none of the user-supplied plot IDs were matched.

**Comment by GregGuerin** [comment]
... you will get the original error message now only if you enter e.g. numbers rather than a vector of quoted text/character
