### ISSUE TITLE
Update growth_form_table by species richness to reflect name handling

### ISSUE THREAD

**Issue by GregGuerin** [ternaustralia/ausplotsR#22]
growth_form_table function has the options to populate GFs x sites by species richness in each GF category. It does this currently by counting unique entries in herbarium_determination by GF

- the output does not contain species names, so defaulting to counting standardised names instead of herbarium names should not affect downstream code

- could either default to standardised names or add as a choice of herbarium versus standardised.

- since names aren't returned, it may make sense not to filter out incomplete IDs etc.

**Comment by Sammunroe** [comment]
to ensure consistency with the other functions, the user can select to use either the standardised name, genus_species, or herbarium_determination.  This may make a difference if they are trying to combine and compare calculations from species_table calculations

I did not include any warnings about making these selections. 

It does not dramatically change results except where there are incomplete ids

Running well on test data.
