### ISSUE TITLE
Visualise ausplots

### ISSUE THREAD

**Issue by GregGuerin** [ternaustralia/ausplotsR#23]
Add function presenting graphical options previously developed for ausplots data visualisation. The aim is for a user to be able to pull the data in one step and then call this function to see selected plots showcasing data.

-the function takes the get_auplots object and user selection of visuals, with the example selecting a handful of plot

-option for live plotting versus save to pdf
-default somehow to prevent attempt to plot stuff out for hundreds of plots without warning to prevent locking up the system?

Some existing options:
-Fractional and growth form cover pie charts per plot
-Species cumulative percent cover as PI samples are taken within plots
-Map of Australia with plot locations marked
-species cover distribution as SAD (species abundance distribution)/Whittaker plot

e.g.,
ausplots_visual(my.ausplots.object, map = TRUE, fractional = TRUE, GF = TRUE, cumulative_cover = TRUE, whittaker = TRUE, file=paste(xx, ".pdf")...)

**Comment by Sammunroe** [comment]
Could we also create a map with the plots, and shade/fill the plots on scale that indicates the cover of a given growth form or species? So for example, if someone was interesting in visualizing the % tree cover (> 5m), see the rough map below.

![Tree_cover](https://user-images.githubusercontent.com/43161345/81523129-0cf04980-938c-11ea-939f-4ab08704a7f7.png)

**Comment by GregGuerin** [comment]
Sounds good - anything that can be calculated internally by calling a function could work and your example could be included by default.

Also, if you don't enter a 'my.ausplots.object' perhaps it should default to extracting a predetermined subset of plots so the user can load the package and just call 'ausplots_visual()' and see some outputs.

**Comment by GregGuerin** [comment]
To structure this function, may be best to have a set of internal functions for each graphical procedure and then the main user function calls upon those as needed.

That makes the code neater and more compartmentalised so features can be added individually, and also means authors can develop code for different visualisations.

**Comment by GregGuerin** [comment]
Bernardo has agreed to including maps similar to that above from his tutorials in this function.

**Comment by Sammunroe** [comment]
ok great, I used ggplot to create this, so perhaps we might think about including ggplot2 as a dependency? Just thinking ahead.
