### ISSUE TITLE
update data selection features in get_ausplots

### ISSUE THREAD

**Issue by Sammunroe** [ternaustralia/ausplotsR#24]
Just a few thoughts...

1.  Update "search_species_name" argument  to use either herbarium_determination or standardised name 

2. Add a "family_search" argument so that the function only extracts plots where that family is detected, essentially mimicking current role of "search_species_name" but for families

**Comment by Sammunroe** [comment]
I have added new search functions:
 herbarium_determination=NULL,  standardised_name=NULL, family=NULL,

Users can search for plots in the category they wish, but only one, trying to do more than one will throw a stop error.  I originally tried to augment the existing search_species_name, but this required a lot of down stream alterations to other aspects of get_ausplots, which I was hesitant to do because it working quite well. This way also seemed more deliberate, in that the user has to actually think about which one they want to use prior to initiating a search.

**Comment by GregGuerin** [comment]
To avoid breaking existing code, might we make the most recommended option the default?

**Comment by Sammunroe** [comment]
Yes, I did have something like that originally and I added it to ausplots_queries, but I wasn't sure then how to get it to work in get_ausplots. 

```
list_available_plots<-function(Plot_IDs=c(),bounding_box="none",species_name_search=NULL,family_search=NULL,herb_determination=FALSE){
extra_query<-list()
if(!is.null(family_search)) {
    extra_query_query = append(extra_query, list("family" = paste("ilike.*", family_search, "*", sep="")))
  }
  if (!is.null(species_name_search)) {
    if(herb_determination){
      extra_query = append( extra_query, list("herbarium_determination" = paste("ilike.*", species_name_search, "*", sep="")))} 
    if(!herb_determination) { 
      extra_query= append( extra_query, list("standardised_name" = paste("ilike.*", species_name_search, "*", sep="")))} 
  }
  if(Plot_IDs[1] == "none") {
    Plot_IDs <- c()
  }
  if(bounding_box[1] != "none") { #i.e. if user has supplied an extent vector
    if(class(bounding_box) != "numeric" | length(bounding_box) != 4) {stop("Bounding box must be a numeric vector of length 4.")}
    min_lon <- bounding_box[1]
    max_lon <- bounding_box[2]
    min_lat <- bounding_box[3]
    max_lat <- bounding_box[4]
    
    extra_query = append(extra_query, list("latitude" = paste("gte.", min_lat, sep="")))
    extra_query = append(extra_query, list("latitude" = paste("lte.", max_lat, sep="")))
    extra_query = append(extra_query, list("longitude" = paste("gte.", min_lon, sep="")))
    extra_query = append(extra_query, list("longitude" = paste("lte.", max_lon, sep="")))
  }
  path <- "search"
  response <- .ausplots_api_with_plot_filter(path, Plot_IDs, extra_query)
  result <- unique(response$site_location_name)
  return(result)
}
```

But then do i need to adjust list_available_plots in get_ausplots? Specifically the call for Plot_IDs? Do I need to add herb_determination=FALSE somehow. Or will it run fine as is?

```
Plot_IDs <- list_available_plots(Plot_IDs=my.Plot_IDs, bounding_box=bounding_box, species name_search=species_name_search, family_search=family_search) 
#add herb_determination=?
  
  # FIXME check when no plots are found and give informative message
	#
	
	if(my.Plot_IDs[1] != "none") {

		if(!class(my.Plot_IDs) == "character") {stop("Plot_IDs must be provided as a character vector.")}
		
		if(all(my.Plot_IDs %in% Plot_IDs)) {cat("User-supplied Plot_IDs located. \n")}
		
		if(!all(my.Plot_IDs %in% Plot_IDs)) { #rules that apply if some user plot IDs aren't matched in the available plot names
			
			if(!any(my.Plot_IDs %in% Plot_IDs)) {stop("None of the user-supplied Plot_IDs match available plot names.")}
			
			cat("Not all user-supplied Plot_IDs match available plot names, only matching plots will be extracted. \n")
			
			my.Plot_IDs <- my.Plot_IDs[which(my.Plot_IDs %in% Plot_IDs)]
			
		} #end if(!all(my.Plot_IDs %in% Plot_IDs)) {
		
		Plot_IDs <- my.Plot_IDs #now the list of plots we will use is just those provided by user after checking they match these available
		
	} #end 	if(my.Plot_IDs !

```

**Comment by GregGuerin** [comment]
Yes, I suspect you'd need to pass the 'herb_determination' argument onto the call of 'list_available_plots' as noted, otherwise I'm guessing the latter will take the default call of FALSE no matter what the user inputs at 'get_ausplots'.

And I think that makes sense as an after-the-fact change - defaulting to our preferred taxonomy but you can ask for the herbarium dets.

**Comment by Sammunroe** [comment]
I have added three new search term functions 
herbarium_determination_search=NULL, family_search=NULL, standardised_name_search=NULL)

As far as I can tell it is running well
