### ISSUE TITLE
ausplotsR producing unneeded warnings when arguments are not supplied 

### ISSUE THREAD

**Issue by Sammunroe** [ternaustralia/ausplotsR#31]
Some functions in ausplotsR are producing warnings when arguments are not supplied by the user and it reverts to the default. The warnings are not causing any harm, they just aren't helpful and potentially a bit confusing. 

For example, for species_table, if m_kind is not supplied, it defaults to m_kind="PA" but produces this warning 

2: In if (m_kind == "PA") { :
  the condition has length > 1 and only the first element will be used
3: In if (m_kind == "percent_cover" | m_kind == "IVI") { :
  the condition has length > 1 and only the first element will be used
4: In if (m_kind == "freq" | m_kind == "IVI") { :
  the condition has length > 1 and only the first element will be used
5: In if (m_kind == "IVI") { :
  the condition has length > 1 and only the first element will be used

if cover_type is not supplied, it defaults to PFC, but gives this warning.

 In if (cover_type == "PFC") { :
  the condition has length > 1 and only the first element will be used

I think it is unlikely that m_kind wouldn't be specified, but cover_type might be ignored. Especially because it is specified as the default in the .Rd help files. The warnings don't effect anything, but they might confuse a user. Maybe we should consider either adding a stop function where if these things are not specified, it produces an error, or adding a missing() function to set the default more officially and remove the warning?

**Comment by GregGuerin** [comment]
@Sammunroe  Adding stop rules with a clear message printed is probably the neatest way to go. The alternative is to only list the desired default in the function definition (i.e., , m_kind="percent_cover") but list the accepted alternatives in the help file. The first option is the easiest as it just stops if the right arguments aren't specified and means you can see the options as the call the function.

**Comment by tomsaleeba** [comment]
I support the "*first option*" as keeping the full list of options in the code makes it easier to maintain (intent is clear) and we get validation of arguments for free from R. "*The alternative*" relies too much on documentation being kept in sync with code (always makes me uneasy) and loses the free argument validation.

There is a builtin R function to make it easy to pull the "default" value from a vector: `match.arg()`. Here's an example usage.

```R
thefn = function(a, b, op=c('add','sub')) {
  # if (op == 'add') { # this line gives a warning because op is a vector
  op = match.arg(op)   # using this re-assigns 'op' variable
  if (op == 'add') {
    return(a+b)
  }
  if (op == 'sub') {
    return(a-b)
  }
}
 
print(thefn(3, 5))                # defaults to 'add' without warning
print(thefn(9, 4, op='sub'))      # explicit valid arg value works
print(thefn(1, 2, op='explode'))  # explicit invalid arg value gives error
```

The downside of this approach when comparing to an `if` is that you don't get the chance to `stop` or show a warning.

**Comment by GregGuerin** [comment]
That sounds pretty good. We could use a more manual warning/stop approach for arguments we want to force the user to specify/choose and this where there is a preferred default.

Another bonus would be that existing code to call the function would work but by having these default arguments choices with no warnings, you'd also be able to call the function with default settings more simply. e.g. for species_table, you might default to percent_cover, PFC and StandardisedName perhaps.

**Comment by GregGuerin** [comment]
@tomsaleeba @Sammunroe I think it is only species_table and growth_form_table and basal_area that present a vector of choices in function arguments (other functions just have data inputs, T/F or a vector that is used as a vector) so hopefully quick to implement Tom's suggestions (PA-presence absence is currently listed first but should be percent cover as default I reckon... ?)

**Comment by Sammunroe** [comment]
Yes, I think those are the only functions with a vector of choices. I agree percent cover makes the most sense as the default.

 Having said that, I am partial to inserting a stop function if m_kind isn't specified only because it forces the users to act with intention. People may ignore a default warning. It does not matter as much if they ignore the default warning for species_name, because we have set it to the best option in most cases. But choosing the wrong m_kind could be very confusing for people if they are not paying attention.
