### ISSUE TITLE
Internet resource fail gracefully CRAN request

### ISSUE THREAD

**Issue by GregGuerin** [ternaustralia/ausplotsR#40]
'Packages which use Internet resources should fail gracefully with an informative message
if the resource is not available or has changed (and not give a check warning nor error).'

Note that https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html only mentions converting API errors to R errors, but policy is now that no error should be thrown.

**Comment by tomsaleeba** [comment]
My interpretation: I think an R error *is* a graceful failure, as long as it gives the user a message that a non-technical person can understand. If the API cannot be reached, nothing can be done. There is no graceful recovery that still allows work to be done.

**Comment by GregGuerin** [comment]
I think we have solved with https://github.com/ternaustralia/ausplotsR/tree/gracefully_fail  - CRAN doesn't want to see any errors in their periodic check reports, e.g. in the run examples.

In get_ausplots, I have added checks at the top for internet, http error or timeout that return a message to the console and a NULL object as output.
