### ISSUE TITLE
How can I obtain the site identity selected by optim_species in the package ausplotsR?

### ISSUE THREAD

**Issue by FrancoisBrassardAnt** [ternaustralia/ausplotsR#69]
I would like to use an optimization method for plot selection that would maximize different diversity indices. For instance, I would like to know which subset of sites I should select to maximize species richness. If I had 3 sites to choose from a total of 4, which ones would get picked 1st, 2nd and 3rd, and how many species would be accumulated at each step?

The function optim_species in the package ausplotsR within R looks promising for this as it provides number of accumulated species for each additional site selected. However, the function does not provide the identity of the selected sites for each diversity metric used.

Is there a way to obtain this information? If not, is there an alternative approach?

`#' See the following example: 
# load package
library(ausplotsR)

# matrix for test
species_matrix <- matrix(
  c(1, 0, 1, 1, 0, 
    0, 0, 1, 0, 0,
    0, 1, 1, 0, 0,
    0, 1, 0, 0, 1),
  nrow = 4,
  ncol = 5,
  byrow = TRUE,
  dimnames = list(c("Site 1", "Site 2", "Site 3", "Site 4"), c("Species 1", "Species 2", "Species 3", "Species 4", "Species 5"))
)

optim_species(species_matrix, n.plt = 3, random = TRUE, iterations = 10) 
`

At the start of the output, I get the chosen sites (a consensus of all estimator perhaps?), but I do not get the site id of the first randomly selected site. Lower in the output, I also do not get the site id selected by each estimator (only the accumulated diversity for number of sites selected). Any help would be greatly appreciated.

Note that I asked this question on StackOverflow and will post the answer there (and give credits of course) if I get answer.
See: https://stackoverflow.com/questions/76910491/how-can-i-obtain-the-site-identity-selected-by-optim-species-in-the-package-ausp

**Comment by GregGuerin** [comment]
Hello,

thanks for this post.

The function returns a species accumulation result object from package vegan (see function specaccum). By default, only some of the object is written to the console when you run this, but you can query the information contained within the object. Each object in your list (one per optimiser) contains a $richness element that is a vector of accumulated richness in order, with the vector names being the site names, which you can use to identify the sites and the order they were selected in.

So,

my_ex <- optim_species(species_matrix, n.plt = 3, random = TRUE, iterations = 10)

str(my_ex)

my_ex$Simpson$richness

>Site 1 Site 4 Site 3 
>   3      5      5 

Does that give you the information you need out of the optimisation?

Cheers,
Greg

**Comment by FrancoisBrassardAnt** [comment]
Hello Greg,

This is exactly what I needed. Thank you so much!

All the best,
François
